language: generic
sudo: required
sevices:
  - docker

before_install:
  - docker build -t harmeet2harry/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harmeet2harry/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-241386660298"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY