language: generic
sudo: required
sevices:
  - docker

before_install:
  - docker build -t harmeet2harry/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harmeet2harry/docker-react npm run test